channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - albumentations=1.2.1
  - cudatoolkit=11.6
  - efficientnet-pytorch=0.7.1
  - imgaug=0.4.0
  - jupyter=1.0.0
  - jupyterlab=3.4.5
  - matplotlib=3.5.3
  - nodejs=16.12.0
  - numpy=1.22.4
  - opencv=4.4.0
  - pandas=1.4.3
  - pip=22.2.2
  - plotly=5.10.0
  - python=3.8.13
  - pytorch=1.12.1
  - pytorch-lightning=1.7.2
  - pyyaml=6.0
  - scikit-image=0.19.3
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - sympy=1.10.1
  - torchaudio=0.12.1
  - torchmetrics=0.9.3
  - torchvision=0.13.1
  - pip:
    - opencv-contrib-python==4.4.0.46
    - opencv-python-headless==4.4.0.46
    - segmentation-models-pytorch==0.3.2
    - timm==0.6.12
    - einops==0.6.0
    - monai==1.1.0
    - fvcore==0.1.5.post20221221
